### ISSUE TITLE
Incorrect color on translated site

### ISSUE THREAD

**Issue by Katsute** [Katsute/GitHub-Red-Issues#21]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I am running the latest release version.

### Operating System

Windows 10

### Browser

Any

### Extension Version

v3.1

### Components

- [ ] Pinned issues
- [X] Closed issues
- [ ] Issue timeline
- [ ] Issues tab
- [ ] Issue hovercard
- [ ] Closed pulls
- [ ] Pull timeline
- [ ] Pull hovercard
- [ ] Subscriptions
- [ ] Search
- [ ] Projects
- [X] Projects (beta)
- [ ] Insights
- [ ] Other (please specify)

### Issue

Projects beta shows wrong color when site is used in another language[^1]: 
https://github-com.translate.goog/users/Katsute/projects/14?_x_tr_sl=en&_x_tr_tl=ja

Caused by aria labels using translated name:
https://github.com/Katsute/GitHub-Red-Issues/blob/6da124f3ac9888a1b12f8b6b7aba5579d1f72820/src/style.css#L44-L46

---

Additionally closed issues will also have the wrong color[^1]:
https://github-com.translate.goog/Katsute/GitHub-Red-Issues/issues/5?_x_tr_sl=en&_x_tr_tl=ja

Caused by titles using translated name:
https://github.com/Katsute/GitHub-Red-Issues/blob/6da124f3ac9888a1b12f8b6b7aba5579d1f72820/src/style.css#L18-L24

---

`aria` and `title` attributes should not be used for determining css

[^1]: Sample is provided to demonstrate that the `aria` and `title` labels are not static. The extension does not run on the google translate domain.

**Comment by krystian3w** [comment]
Yandex have similar own domains:

```
https://z5h64q92x9.net/proxy_u/en-de.en.629ad9c9-622e3bbe-777761c0-74722d776562/https/github.com/Katsute/GitHub-Red-Issues/issues/21
```


 also on Firefox with disabled CSP works scritplet:

```js
javascript:(function()%7Bd%20%3D%20document%3Bb%20%3D%20d.body%3Bo%20%3D%20d.createElement('scri'%20%2B%20'pt')%3Bo.setAttribute('src'%2C%20'https%3A%2F%2Ftranslate.google.com%2Ftranslate_a%2Felement.js%3Fcb%3DgoogleTranslateElementInit')%3Bo.setAttribute('type'%2C%20'text%2Fjavascript')%3Bb.appendChild(o)%3Bv%20%3D%20b.insertBefore(d.createElement('div')%2C%20b.firstChild)%3Bv.id%20%3D%20'google_translate_element'%3Bv.style.display%20%3D%20'none'%3Bp%20%3D%20d.createElement('scri'%20%2B%20'pt')%3Bp.text%20%3D%20'function%20googleTranslateElementInit()%7Bnew%20google.translate.TranslateElement(%7BpageLanguage%3A%22%22%7D%2C%22google_translate_element%22)%3B%7D'%3Bp.setAttribute('type'%2C%20'text%2Fjavascript')%3Bb.appendChild(p)%7D)()
```

or these addon:

https://addons.mozilla.org/pl/firefox/addon/s3_translator/
