### ISSUE TITLE
Issue Closed Reason

### ISSUE THREAD

**Issue by Katsute** [Katsute/GitHub-Red-Issues#40]
### Prerequisites

- [X] I have checked that no other similar issue already exists.
- [X] I have checked that this issue is actually a bug and not a feature.
- [X] I am running the latest release version.

### Operating System

*

### Browser

n/a

### Extension Version

n/a

### Components

- [X] Pinned issues
- [X] Closed issues
- [X] Issue timeline
- [X] Issues tab
- [X] Issue hovercard
- [ ] Closed pulls
- [ ] Pull timeline
- [ ] Pull hovercard
- [X] Subscriptions
- [X] Search
- [X] Projects
- [X] Projects (beta)
- [X] Insights
- [ ] Other (please specify)

### Issue

https://github.blog/changelog/2022-05-19-the-new-github-issues-may-19th-update/

Issues now have two closed states - completed and won't fix, css selectors need to be rechecked.

Closed/completed should be red, closed/wontfix should be gray.

**Comment by Katsute** [comment]
Extension already compatible with closed/not planned. Certain closed/not planned issues use the wrong icon, caused by GitHub, no changes to extension are needed.

**Comment by krystian3w** [comment]
Guests/Google Translaters have purple and red with addon - maybe possible use API to recover classes/attributes.

**Comment by Katsute** [comment]
That issue was solved in #22 as part of v3.2, that version will be released as soon as it goes through some QA testing.

**Comment by Katsute** [comment]
GitHub seems to have not implemented the closed/not-planned correctly, certain pages still use the regular closed icon for these issues. The extension should work properly when they fix these issues.

(Logged in)
![image](https://user-images.githubusercontent.com/58778985/169412468-c4a75422-9a36-4823-bff9-c8eb210d89ec.png)

(Incognito tab)
![image](https://user-images.githubusercontent.com/58778985/169412488-23b180bd-8d61-435d-8f93-9fc5a4243e8e.png)
