### ISSUE TITLE
JS can be removed

### ISSUE THREAD

**Issue by Katsute** [Katsute/GitHub-Red-Issues#7]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

Remove js

### Reason

Closed pull request timeline now correctly has `color-bg-danger-emphasis` instead of `color-bg-done-emphasis`. JS workaround for fixing the CSS is no longer needed.

**Comment by Katsute** [comment]
Added in v2

**Comment by krystian3w** [comment]
CSS file no have changes - is older than this issue. this is correct behavior if MS landed `color-bg-danger-emphasis`?

**Comment by Katsute** [comment]
This behavior is correct, the GitHub site fixed the css for the timeline.

**Comment by krystian3w** [comment]
So not your oldie css created html class:

`.rissue-merge`

**Comment by Katsute** [comment]
That class was used to fix a confliction between pull merge and pull close timeline icons. GitHub recently fixed it so both the class and JS are no longer needed.

**Comment by krystian3w** [comment]
So in the v2.2 we can try cleanup a little "style.css" file or bettter mark to "won't fix" as long rebuild logic in css file?

**Comment by Katsute** [comment]
I'll clean up that css as part of the next release.
