### ISSUE TITLE
reborn fork for Firefox

### ISSUE THREAD

**Issue by krystian3w** [Katsute/GitHub-Red-Issues#9]
### Prerequisites

- [X] I have checked that no other similar feature request already exists.
- [X] This feature request makes sense for the project.
- [X] I have checked that this feature does not already exist.
- [X] I am running the latest release version.

### Feature

reborn forked repo https://github.com/iam-py-test/GitHub-Red-Closed-Issues-Extension / maybe enable shorter name https://github.com/iam-py-test/GitHub-Red-Issues (but then long name no longer works, GitHub/MS issue).

### Reason

Was active in the past.

**Comment by krystian3w** [comment]
https://github.com/Katsute/GitHub-Red-Issues/commit/b5fa8aa2dad77dff41411552cc870f34173ae59d#commitcomment-62255818 - maybe run again in 21.12.2021.

**Comment by krystian3w** [comment]
See also https://github.com/Katsute/GitHub-Red-Issues/pull/10

**Comment by Katsute** [comment]
@iam-py-test @krystian3w Mozilla Firefox is now officially supported

**Comment by iam-py-test** [comment]
> @iam-py-test @krystian3w Mozilla Firefox is now officially supported

Ok, I'll put a note in the README
